# Generated by Django 4.2.1 on 2023-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testlist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('mail', models.CharField(max_length=20)),
                ('prefecture_no', models.IntegerField()),
                ('prefecture_name', models.CharField(max_length=255)),
                ('prefecture_kana', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'testlist',
                'managed': False,
            },
        ),
    ]
