# Generated by Django 4.2.1 on 2023-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefectureMst',
            fields=[
                ('prefecture_no', models.IntegerField(primary_key=True, serialize=False)),
                ('prefecture_name', models.CharField(max_length=255)),
                ('prefecture_kana', models.CharField(max_length=255)),
                ('regist_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('del_flg', models.IntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name='testlist',
            table='prefecture_mst',
        ),
    ]
