# Generated by Django 4.2.1 on 2023-05-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_prefecturemst_alter_testlist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testlist',
            table='testlist',
        ),
    ]
