# Generated by Django 4.2.1 on 2023-05-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_alter_testlist_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefecturemst',
            options={'managed': False},
        ),
    ]
